apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ template "trackableappname" . }}-ssl"
spec:
  secretName: "{{ template "trackableappname" . }}-ssl"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.domain }}
  dnsNames:
    - {{ .Values.ingress.domain }}
  acme:
    config:
      - http01:
          ingressClass: istio
        domains:
          - {{ .Values.ingress.domain }}
