apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ template "trackableappname" . }}"
spec:
  hosts:
    - "{{ .Values.ingress.domain }}"
  gateways:
    - "{{ template "trackableappname" . }}-gateway"
  http:
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: lada-lecar-api-dev
            port:
              number: 80
    - route:
      - destination:
          host: {{ template "trackableappname" . }}
          port:
            number: {{ .Values.service.externalPort }}
